[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/desktop"
  to = "/desktop.html"
  status = 200

[[redirects]]
  from = "/mobile"
  to = "/mobile.html"
  status = 200
