services:
  - type: web
    name: pocketterminal-api
    env: python
    plan: free
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:$PORT --timeout 120 app:app
    envVars:
      - key: POCKET_ENV
        value: production
      - key: POCKET_ENABLE_ML
        value: "0"
      - key: POCKET_SSL
        value: "0"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
